#!/bin/bash

set -o errexit
set -o nounset

NOW=$(date "+%D %T")
LOG_FILE="/tmp/steam-session.log"

if [[ -e ${LOG_FILE} ]]; then
    mv "${LOG_FILE}" "${LOG_FILE}.old"
    touch "${LOG_FILE}"
fi

function logger {
    local LEVEL=$1

    if [[ $# -ge 2 && -n "$2" ]]; then
        MESSAGE=$2
        echo "${NOW} - [${LEVEL}] - ${MESSAGE}" >> ${LOG_FILE}
    else
        while read -r MESSAGE; do
            echo "${NOW} - [${LEVEL}] - ${MESSAGE}" >> ${LOG_FILE}
        done
    fi
}

function check_process {
    local NAME=$1

    pgrep "${NAME}" && return 0 || return 1
}

function monitor_process {
    local NAME=$1
    local COMMAND=$2

    while true; do
        if ! check_process "$NAME"; then
            logger "WARNING" "${NAME^} has stopped. Restarting"
            eval "$COMMAND" > /dev/null 2>&1
        else
            sleep 1
        fi
    done
}

logger "INFO" "Starting Steam session"

logger "INFO" "Starting window manager"
openbox-session 1>/dev/null 2> >(logger "WARNING") &

sleep 0.1

logger "INFO" "Disabling screensaver and screen energy saving mode"
xset s off -dpms 1>/dev/null 2> >(logger "WARNING") &

sleep 0.1

logger "INFO" "Hiding the mouse cursor"
unclutter --start-hidden 1>/dev/null 2> >(logger "WARNING") &

sleep 0.1

logger "INFO" "Starting Steam in big picture mode"
steam -bigpicture > /dev/null 2>&1 &

sleep 5

logger "INFO" "Starting to monitor Steam"
monitor_process "steam" "steam -bigpicture"